corda/corda-solutions

- docs/source/business-networks/interoperability.rst
incorporate some of Cristina review comments.
> Edit interoperability

- docs/source/business-networks/business-network-playbook/intro.rst
Edit BN playbook intro per Cristina doc review
> Edit BN playbook intro

- docs/source/business-networks/business-network-playbook/operations.rst
edit BN Playbook Operations doc
> edit BN Playbook Operations doc

- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/bno/RevokeMembershipFlow.kt
Added `@StartableByRPC` to `RevokeMembershipFlow`.
> bugfix-rpc-annotation

- bn-apps/memberships-management/README.md
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/bno/RequestMembershipFlowResponder.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/bno/extension/BNODecisionMaker.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/bno/extension/MembershipAutoAcceptor.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/bno/service/BNOConfigurationService.kt
- bn-apps/memberships-management/membership-service/src/test/kotlin/net/corda/businessnetworks/membership/ActivateMembershipFlowTest.kt
- bn-apps/memberships-management/membership-service/src/test/kotlin/net/corda/businessnetworks/membership/customizations/DummyMembershipAutoAcceptor.kt
- bn-apps/memberships-management/membership-service/src/test/resources/membership-service-with-auto-approver.properties
This was necessary for Leia. At the same time I made it generic enough to be reusable.
> Introducing a hook to allow auto activation of membership

- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/Exceptions.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/bno/RequestMembershipFlowResponder.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/bno/extension/MembershipAutoAcceptor.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/bno/support/BusinessNetworkOperatorFlowLogic.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/bno/support/BusinessNetworkOperatorInitiatedFlow.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/common/PartyAndMembershipMetadata.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/member/GetMembershipsFlow.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/member/support/BusinessNetworkAwareInitiatedFlow.kt
- bn-apps/memberships-management/membership-service/src/test/kotlin/net/corda/businessnetworks/membership/ActivateMembershipFlowTest.kt
- bn-apps/memberships-management/membership-service/src/test/kotlin/net/corda/businessnetworks/membership/GetMembershipsFlowTest.kt
- bn-apps/memberships-management/membership-service/src/test/kotlin/net/corda/businessnetworks/membership/RevokeMembershipFlowTest.kt
Refactoring, moved some classes around
> Refactoring, moved some classes around

- bn-apps/memberships-management/design/design.md
Corrected typo in Membership service design doc
> fixed Transaction structure for metadata amendment

- bn-apps/build.gradle
- bn-apps/gradle/wrapper/gradle-wrapper.properties
- bn-apps/ledger-sync/ledger-sync-service/build.gradle
- bn-apps/memberships-management/membership-service-contracts-and-states/build.gradle
- bn-apps/memberships-management/membership-service/build.gradle
Bumped up gradle and kotlin versions
> Bumped up gradle and kotlin versions

- docs/conf.json
Added configuration for docs build
> Added configuration for docs build

- docs/source/corda-modelling-notation/intro-to-cmn.rst
> intro corrections

- bn-apps/memberships-management/membership-service/src/main/kotlin/net/corda/businessnetworks/membership/bno/service/DatabaseService.kt
Changed BNMS service to use parameterised SQL queries to prevent SQL injections (even though it's just a party name)
> Changed BNMS service to use parameterised SQL queries

- CONTRIBUTORS.md
- README.md
- docs/README.md
* Update contributors.
* Add new top-level README.
* Switch to more conventional MD formatting for the docs README.
> Update documentation files for the git repo.

- docs/requirements.txt
Bumped up version of requests library to remove github warning
> Bumped up version of requests library to remove github warning

- docs/source/corda-modelling-notation/views/views-bpmn.rst
fix the missing picture in bpmn view
> fix picture in bpmn view

- build.gradle
Bumped up the version to 2.0 snapshot
> Bumped up the version

- .gitignore
- bn-apps/cordapp-updates-distribution/README.md
- bn-apps/ledger-sync/readme.rst
- bn-apps/memberships-management/README.md
Added information about how to include bn-apps to a project
> Info how to add bn apps to your project

- bn-apps/README.md
- bn-apps/cordapp-updates-distribution/README.md
- bn-apps/ledger-sync/readme.rst
- bn-apps/memberships-management/README.md
1. Added a header to each of the services READMEs about corda-v4 branch
2. Fixed mistakes in package namespaces
> Added header about corda v4

- bn-apps/README.md
- bn-apps/cordapp-updates-distribution/README.md
- bn-apps/ledger-sync/readme.rst
- bn-apps/memberships-management/README.md
Fixed versions and typos in readmes
> Fixed readmes

- bn-apps/billing/README.md
- bn-apps/cordapp-updates-distribution/README.md
- bn-apps/ledger-sync/readme.rst
- bn-apps/memberships-management/README.md
- build.gradle
Bumped up version to 3.0-SNAPSHOT. 
Updated docs.
> Bumped up version to 3.0-SNAPSHOT

- docs/requirements.txt
Fixed dependency warning for Jinja library
> Fixed dependency warning for Jinja

- bn-apps/billing/README.md
- bn-apps/billing/billing-demo/README.md
Adds short deployment instructions for billing app and for billing demo
> Add config note

- bn-apps/billing/billing-app/build.gradle
- bn-apps/billing/billing-demo/build.gradle
Fatjarred businessnetworks-utiities into the billing app
> Fatjarred businessnetworks-utiities into the billing app

- bn-apps/memberships-management/README.md
- bn-apps/memberships-management/membership-service/src/main/kotlin/com/r3/businessnetworks/membership/flows/bno/ActivateMembershipFlow.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/com/r3/businessnetworks/membership/flows/bno/RequestMembershipFlowResponder.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/com/r3/businessnetworks/membership/flows/bno/SelfIssueMembershipFlow.kt
- bn-apps/memberships-management/membership-service/src/main/kotlin/com/r3/businessnetworks/membership/flows/member/RequestMembershipFlow.kt
- bn-apps/memberships-management/membership-service/src/test/kotlin/com/r3/businessnetworks/membership/flows/SelfIssueMembershipFlowTest.kt
Modified the README to include the SelfIssueMembershipFlow and modified SelfIssueMembershipFlow
to run the NotifyActiveMembersFlow to alert other members.
> Couple of small changes for SelfIssueMembership

- bn-apps/memberships-management/membership-service/src/main/kotlin/com/r3/businessnetworks/membership/flows/member/ActivateMembershipFlowResponder.kt
@ivanr3 Forgot one check, please review/accept this PR.
> Added a check that I missed for BNO is member case on ActivateMembership

- bn-apps/ledger-sync/ledger-sync-service/src/main/kotlin/com/r3/businessnetworks/ledgersync/EvaluateLedgerConsistencyFlow.kt
- bn-apps/ledger-sync/ledger-sync-service/src/main/kotlin/com/r3/businessnetworks/ledgersync/Helpers.kt
- bn-apps/ledger-sync/ledger-sync-service/src/main/kotlin/com/r3/businessnetworks/ledgersync/RequestLedgersSyncFlow.kt
- bn-apps/ledger-sync/ledger-sync-service/src/test/resources/ledgersync.conf
load ContractState page by page with default page size = 200
> Load ContractState by page

- bn-apps/memberships-management/membership-service/src/main/kotlin/com/r3/businessnetworks/membership/flows/bno/SelfIssueMembershipFlow.kt
- bn-apps/memberships-management/membership-service/src/test/kotlin/com/r3/businessnetworks/membership/flows/AbstractFlowTest.kt
- bn-apps/memberships-management/membership-service/src/test/kotlin/com/r3/businessnetworks/membership/flows/SelfIssueMembershipFlowTest.kt
New code with request membership and activate membership in one flow
> [PSA-5] The BNO can become a member

- bn-apps/ledger-sync/ledger-sync-service/src/main/kotlin/com/r3/businessnetworks/ledgersync/Helpers.kt
add logger
modify some comment
> add logger for ConfigurationService

- docs/source/deployment/corda-health-checker.rst
- docs/source/deployment/intro.rst
> Update Health Checker Tool

- bn-apps/billing/README.md
Current one refers to the deleted branch.
> Fix broken link in the README

- build.gradle
Update Artifactory URLs to use `https` everywhere and the `software.r3.com` endpoint.
> NOTICK Update Artifactory URLs
